In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('survey_results_schema.csv', index_col='Column')

In [3]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [4]:
df.head(4)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

In [5]:
df['ConvertedComp'].head(15)

Respondent
1          NaN
2          NaN
3       8820.0
4      61000.0
5          NaN
6     366420.0
7          NaN
8          NaN
9      95179.0
10     13293.0
11         NaN
12         NaN
13     90000.0
14     57060.0
15         NaN
Name: ConvertedComp, dtype: float64

In [6]:
df['ConvertedComp'].median()

57287.0

In [12]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

newdf = df.select_dtypes(include=numerics)
newdf

            CompTotal  ConvertedComp  WorkWeekHrs  CodeRevHrs   Age
Respondent
1                 NaN            NaN          NaN         NaN  14.0
2                 NaN            NaN          NaN         NaN  19.0
3             23000.0         8820.0         40.0         NaN  28.0
4             61000.0        61000.0         80.0         NaN  22.0
5                 NaN            NaN         55.0         NaN  30.0
...               ...            ...          ...         ...   ...
43135             NaN            NaN          NaN         NaN  22.0
43136        350000.0       350000.0         80.0         2.0  29.0
43137             NaN            NaN          NaN         NaN   NaN
43138             NaN            NaN         40.0         NaN  33.0
43139          8000.0        26232.0         44.0         2.0  28.0

[42866 rows x 5 columns]

In [11]:
newdf.median() # this didnt work directly for me, so i had to find all numeric value columns on dataframe, then use this

CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [13]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  2.706400e+04   2.700200e+04  31247.000000  24089.000000  38300.000000
mean   1.140843e+12   1.267713e+05     42.230408      5.123749     30.356355
std    1.054129e+14   2.844290e+05     39.302576      5.667326      9.154431
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.566800e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.000000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4125.000000     99.000000     99.000000

In [15]:
df['ConvertedComp'].count()

27002

In [16]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
43135    Yes
43136    Yes
43137    Yes
43138    Yes
43139    Yes
Name: Hobbyist, Length: 42866, dtype: object

In [19]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    34414
No      8452
Name: count, dtype: int64

In [20]:
df['SocialMedia']

Respondent
1          Twitter
2        Instagram
3           Reddit
4           Reddit
5         Facebook
           ...
43135      YouTube
43136      Twitter
43137      YouTube
43138      Twitter
43139     WhatsApp
Name: SocialMedia, Length: 42866, dtype: object

In [21]:
df['SocialMedia'].value_counts()

SocialMedia
Reddit                      7074
YouTube                     6597
WhatsApp                    6465
Facebook                    6366
Twitter                     5606
Instagram                   2997
I don't use social media    2697
LinkedIn                    2118
WeChat 微信                    315
Snapchat                     304
VK ВКонта́кте                271
Weibo 新浪微博                    29
Youku Tudou 优酷                13
Hello                         12
Name: count, dtype: int64

In [22]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [23]:
df['SocialMedia'].value_counts(normalize=True)

SocialMedia
Reddit                      0.173111
YouTube                     0.161438
WhatsApp                    0.158208
Facebook                    0.155785
Twitter                     0.137187
Instagram                   0.073341
I don't use social media    0.065999
LinkedIn                    0.051830
WeChat 微信                   0.007708
Snapchat                    0.007439
VK ВКонта́кте               0.006632
Weibo 新浪微博                  0.000710
Youku Tudou 优酷              0.000318
Hello                       0.000294
Name: proportion, dtype: float64

In [25]:
df['Country'].value_counts()

Country
United States     10117
India              4373
Germany            2815
United Kingdom     2736
Canada             1654
                  ...
Guinea                1
Gabon                 1
Sierra Leone          1
Mali                  1
Bhutan                1
Name: count, Length: 175, dtype: int64

In [27]:
country_grp = df.groupby(['Country'])

In [29]:
country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43084,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,100 to 499 employees,"Developer, mobile",7,18,5,Slightly satisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,Complete a take-home project;Interview with pe...,No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",INR,Indian rupee,2400000.0,Yearly,33583.0,48.0,There's no schedule or spec; I work on what se...,Not enough people for the workload;Time spent ...,Less than once per month / Never,Office,Far above average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have some influence,Java;Kotlin,Dart;Swift,Firebase;Microsoft SQL Server;MySQL;SQLite,NaN,Android,Arduino;iOS,NaN,NaN,NaN,NaN,Android Studio;IntelliJ;Sublime Text;Visual St...,MacOS,NaN,Not at all,NaN,No,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2010,A few times per month or weekly,Find answers to specific questions,Less than once per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers,NaN,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
43095,I am a student who is learning to code,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",NaN,"Designer;Developer, back-end;Developer, deskto...",2,10,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,Office environment or company culture;Opportun...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;C#;HTML/C...,Assembly;C;C++;C#;Clojure;Dart;Go;JavaScript;K...,NaN,Elasticsearch;Firebase;MongoDB;MySQL;PostgreSQ...,Docker;Linux;Slack,Android;Arduino;Docker;Heroku;Linux;Raspberry ...,Django;jQuery,Angular/Angular.js;Django;Express;Flask;React....,.NET Core;Unity 3D;Unreal Engine,Flutter;.NET Core;Node.js;React Native,Vim;Visual Studio Code,Linux-based,"Development;Testing;Outside of work, for perso...",NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,Twitter,Online,Username,2014,A few times per month or weekly,Find answers to specific questions;Contribute ...,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Too long,Neither easy nor difficult
43121,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,20 to 99 employees,"Developer, back-end;Developer, desktop or ente...",8,13,3,Very satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write code by hand (e.g., on a whiteboard);Sol...",Yes,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",INR,Indian rupee,NaN,NaN,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,NaN,Office,Average,"Yes, because I see value in code review",2.0,"Yes, it's not part of our process but the deve...",NaN,NaN,C;C++;C#;HTML/CSS;Java;JavaScript;PHP;SQL;Type...,HTML/CSS;JavaScript;PHP;SQL;TypeScript;Other(s):,Firebase;MySQL;SQLite,MySQL,Android;IBM Cloud or Watson;Linux;Microsoft Az...,Linux;WordPress,Angular/Angular.js;Django;jQuery;Laravel;React.js,Drupal;jQuery;Laravel;React.js,Node.js,Node.js;React Native;Unity 3D,Eclipse;NetBeans;Notepad++;Sublime Text;Visual...,Linux-based,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",No,Twitter,Online,NaN,2016,A few times per week,Find answers to specific questions;Contribute ...,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,NaN,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
43135,I am a student who is learning to code,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,NaN,Data scientist or machine learning specialist;...,3,19,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,"Languages, frameworks, and other technologies ...",I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;Python;SQL,Bash/Shell/PowerShell;C#;Elixir;Go;Java;Kotlin...,Firebase;MySQL;PostgreSQL,Cassandra;DynamoDB;Firebase;MongoDB;MySQL;Post...,Android;AWS;Google Cloud Platform;IBM Cloud or...,Android;AWS;Google Cloud Platform;IBM Cloud or...,NaN,Angular/Angular.js;Django;Flask;jQuery;React.j...,NaN,Apache Spark;Cordova;CryEngine;Hadoop;Pandas;T...,Android Studio;Atom;IntelliJ;NetBeans;PyCharm;...,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,YouTube,Online,Handle,2016,Daily or almost daily,Find answers to specific questions;Contribute ...,More than 10 times per week,They were about the same,NaN,Yes,Daily or almost daily,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
43137,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Received on-the-job training in software devel...,100 to 499 employees,"Developer, back-end;Developer, front-end",4,26,4,Slightly satisfied,Neither satisfied nor dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in senior / management r...,No,Opportunities for professional development;Div...,I heard about a job opportunity (from a recrui...,INR,Indian rupee,NaN,Monthly,NaN,NaN,There's no schedule or spec; I work on what se...,Distracting work environment;Lack of support f...,Less than once per month / Never,Home,Average,No,NaN,"Yes, it's part of our process",Not sure,I have little or no influence,PHP;SQL,Python,MySQL,MongoDB;Oracle,WordPress,Android,jQuery,Angular/Angular.js;Laravel;React.js,NaN,NaN,Sublime Text,Linux-based,Development,NaN,NaN,No,"Fortunately, someone else has that title",Yes,YouTube,Online,Username,NaN,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,NaN,NaN,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult

In [32]:
filt = df['Country'] == 'India'
df.loc[filt]['SocialMedia'].value_counts()

SocialMedia
WhatsApp                    1461
YouTube                      889
LinkedIn                     455
Facebook                     421
Instagram                    381
Twitter                      257
Reddit                       223
I don't use social media     126
Snapchat                      10
WeChat 微信                      3
Hello                          2
VK ВКонта́кте                  2
Weibo 新浪微博                     1
Youku Tudou 优酷                 1
Name: count, dtype: int64

In [38]:
country_grp['SocialMedia'].value_counts().head(50)

Country              SocialMedia
Afghanistan          Facebook                      7
                     I don't use social media      2
                     YouTube                       2
                     WhatsApp                      1
                     Instagram                     1
Albania              Facebook                      9
                     WhatsApp                      8
                     Instagram                     7
                     Twitter                       5
                     LinkedIn                      5
                     Reddit                        4
                     I don't use social media      3
                     YouTube                       3
                     Snapchat                      1
                     WeChat 微信                     1
Algeria              YouTube                      19
                     Facebook                     18
                     Twitter                      10
                     Instagram                     6
                     I don't use social media      4
                     LinkedIn                      3
                     WhatsApp                      2
Andorra              I don't use social media      1
                     YouTube                       1
Angola               Twitter                       1
Antigua and Barbuda  Facebook                      1
                     YouTube                       1
Argentina            WhatsApp                    103
                     Twitter                      39
                     YouTube                      29
                     Reddit                       27
                     Facebook                     22
                     Instagram                    17
                     I don't use social media     12
                     LinkedIn                      9
Armenia              Facebook                     23
                     YouTube                      14
                     LinkedIn                      2
                     Twitter                       2
                     Reddit                        1
                     VK ВКонта́кте                 1
                     Instagram                     1
Australia            Reddit                      203
                     Facebook                    157
                     Twitter                     131
                     YouTube                     122
                     WhatsApp                     79
                     I don't use social media     73
                     Instagram                    61
                     LinkedIn                     42
Name: count, dtype: int64

In [41]:
country_grp['SocialMedia'].value_counts().loc['Russian Federation']

SocialMedia
VK ВКонта́кте               199
YouTube                     153
Twitter                      79
Reddit                       76
I don't use social media     71
Instagram                    51
WhatsApp                     48
Facebook                     25
LinkedIn                     13
Name: count, dtype: int64

In [46]:
country_grp['SocialMedia'].value_counts(normalize=True).loc['Russian Federation']

SocialMedia
VK ВКонта́кте               0.278322
YouTube                     0.213986
Twitter                     0.110490
Reddit                      0.106294
I don't use social media    0.099301
Instagram                   0.071329
WhatsApp                    0.067133
Facebook                    0.034965
LinkedIn                    0.018182
Name: proportion, dtype: float64

In [47]:
country_grp['ConvertedComp'].median()

Country
Afghanistan                              2796.0
Albania                                 11040.0
Algeria                                  6354.0
Andorra                                     NaN
Angola                                   7764.0
                                         ...
Venezuela, Bolivarian Republic of...    12000.0
Viet Nam                                10344.0
Yemen                                   13854.0
Zambia                                   8823.5
Zimbabwe                                18000.0
Name: ConvertedComp, Length: 175, dtype: float64

In [48]:
country_grp['ConvertedComp'].median().loc['Turkey']

17280.0

In [49]:
country_grp['ConvertedComp'].agg(['median', 'mean'])

                                       median          mean
Country
Afghanistan                            2796.0   6025.500000
Albania                               11040.0  29253.115385
Algeria                                6354.0   7634.200000
Andorra                                   NaN           NaN
Angola                                 7764.0   7764.000000
...                                       ...           ...
Venezuela, Bolivarian Republic of...  12000.0  22720.181818
Viet Nam                              10344.0  19483.179487
Yemen                                 13854.0  13854.000000
Zambia                                 8823.5   8950.750000
Zimbabwe                              18000.0  19285.714286

[175 rows x 2 columns]

In [50]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Turkey']

median    17280.000000
mean      23900.979253
Name: Turkey, dtype: float64

In [55]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

1492

In [56]:
country_grp['LanguageWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [57]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              3
Albania                                 15
Algeria                                 13
Andorra                                  0
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    16
Viet Nam                                41
Yemen                                    1
Zambia                                   1
Zimbabwe                                10
Name: LanguageWorkedWith, Length: 175, dtype: int64

In [61]:
# country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum()).value_counts(normalize=True)

In [62]:
country_respondents = df['Country'].value_counts()
country_respondents

Country
United States     10117
India              4373
Germany            2815
United Kingdom     2736
Canada             1654
                  ...
Guinea                1
Gabon                 1
Sierra Leone          1
Mali                  1
Bhutan                1
Name: count, Length: 175, dtype: int64

In [63]:
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              3
Albania                                 15
Algeria                                 13
Andorra                                  0
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    16
Viet Nam                                41
Yemen                                    1
Zambia                                   1
Zimbabwe                                10
Name: LanguageWorkedWith, Length: 175, dtype: int64

In [64]:
python_df = pd.concat([country_respondents, country_uses_python], axis='columns', sort=False)
python_df

                count  LanguageWorkedWith
Country
United States   10117                4882
India            4373                1492
Germany          2815                1189
United Kingdom   2736                1131
Canada           1654                 772
...               ...                 ...
Guinea              1                   1
Gabon               1                   0
Sierra Leone        1                   1
Mali                1                   1
Bhutan              1                   1

[175 rows x 2 columns]

In [66]:
python_df.rename(columns={'count':'Number of respondents', 'LanguageWorkedWith': 'NumKnowsPython'}, inplace=True)

In [67]:
python_df

                Number of respondents  NumKnowsPython
Country
United States                   10117            4882
India                            4373            1492
Germany                          2815            1189
United Kingdom                   2736            1131
Canada                           1654             772
...                               ...             ...
Guinea                              1               1
Gabon                               1               0
Sierra Leone                        1               1
Mali                                1               1
Bhutan                              1               1

[175 rows x 2 columns]

In [74]:
python_df['PctKnowsPython'] = ( python_df['NumKnowsPython'] / python_df['Number of respondents'] ) * 100
python_df

                Number of respondents  NumKnowsPython  PctKnowsPython
Country
United States                   10117            4882       48.255412
India                            4373            1492       34.118454
Germany                          2815            1189       42.238011
United Kingdom                   2736            1131       41.337719
Canada                           1654             772       46.674728
...                               ...             ...             ...
Guinea                              1               1      100.000000
Gabon                               1               0        0.000000
Sierra Leone                        1               1      100.000000
Mali                                1               1      100.000000
Bhutan                              1               1      100.000000

[175 rows x 3 columns]

In [76]:
python_df.sort_values(by='PctKnowsPython', ascending=False, inplace=True)

In [78]:
python_df.head(50)

,Number of respondents,NumKnowsPython,PctKnowsPython
Country,,,
Bhutan,1,1,100.000000
Timor-Leste,1,1,100.000000
Benin,3,3,100.000000
Oman,4,4,100.000000
Niger,1,1,100.000000
Dominica,1,1,100.000000
Angola,1,1,100.000000
Guinea,1,1,100.000000
Sierra Leone,1,1,100.000000
Mali,1,1,100.000000
"Congo, Republic of the...",5,4,80.000000
Turkmenistan,5,4,80.000000
Namibia,4,3,75.000000
Uganda,30,20,66.666667
Haiti,3,2,66.666667
Guyana,3,2,66.666667
Iceland,23,13,56.521739
Uzbekistan,9,5,55.555556
Republic of Korea,19,10,52.631579
Finland,267,137,51.310861
Iraq,14,7,50.000000
Mongolia,10,5,50.000000
United Republic of Tanzania,14,7,50.000000
Ethiopia,20,10,50.000000
Mauritania,4,2,50.000000
Rwanda,6,3,50.000000
Bahamas,2,1,50.000000
Monaco,2,1,50.000000
Barbados,2,1,50.000000
Burundi,2,1,50.000000
Liechtenstein,2,1,50.000000
Taiwan,89,44,49.438202
Ecuador,43,21,48.837209
South Korea,76,37,48.684211
China,329,159,48.328267
United States,10117,4882,48.255412
Japan,189,91,48.148148
Zimbabwe,21,10,47.619048
Switzerland,480,226,47.083333
Honduras,17,8,47.058824
Chile,100,47,47.000000
Canada,1654,772,46.674728
Cuba,15,7,46.666667
Panama,15,7,46.666667
Israel,458,206,44.978166
France,1174,527,44.889267
Nepal,109,48,44.036697
Russian Federation,824,358,43.446602
Thailand,99,43,43.434343
Denmark,279,121,43.369176

In [81]:
python_df.loc['Japan']

Number of respondents    189.000000
NumKnowsPython            91.000000
PctKnowsPython            48.148148
Name: Japan, dtype: float64